app/src/Entity/Detail.php
<?php

namespace App\Entity;

use App\Repository\DetailRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DetailRepository::class)
 */
class Detail
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $action;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $money;

    /**
     * @ORM\Column(type="integer")
     */
    private $current_balance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $remark;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="detail")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAction(): ?string
    {
        return $this->action;
    }

    public function setAction(string $action): self
    {
        $this->action = $action;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getMoney(): ?int
    {
        return $this->money;
    }

    public function setMoney(int $money): self
    {
        $this->money = $money;

        return $this;
    }

    public function getRemark(): ?string
    {
        return $this->remark;
    }

    public function setRemark(?string $remark): self
    {
        $this->remark = $remark;

        return $this;
    }

    public function getCurrentBalance(): ?int
    {
        return $this->current_balance;
    }

    public function setCurrentBalance(int $current_balance): self
    {
        $this->current_balance = $current_balance;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

app/src/Controller/DetailController.php
<?php

namespace App\Controller;

use App\Repository\DetailRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

class DetailController extends AbstractController
{
    /**
     * @Route("/detail", name="detail")
     */
    public function index(DetailRepository $detailRepository, Security $security): Response
    {
        $details = $detailRepository->findBy(['user' => $security->getUser()], ['id' => 'DESC']);

        return $this->render('detail/index.html.twig', [
            'details' => $details,
        ]);
    }
}

app/templates/detail/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}交易紀錄{% endblock %}

{% block body %}
    <table class="table table-striped" style="margin-top: 50px;">

        <thead>
            <tr>
                <td></td>
                <td>存款</td>
                <td>提款</td>
                <td style="width: 260px;">餘額</td>
                <td style="width: 160px;">時間</td>
                <td style="width: 120px;">註記</td>

            </tr>
        </thead>

        <tbody>
            {% if (details|length) > 0 %}
                {% for detail in details %}
                    <tr class='clickable-row'>
                        <td>{{ loop.index == 1 ? '1(最新資料)':loop.index }}</td>
                        <td>{{ detail.action == 'Deposit' ? detail.money:'' }}</td>
                        <td>{{ detail.action == 'Withdrawal' ? detail.money:'' }}</td>
                        <td style="color: red">{{ detail.currentBalance }}</td>
                        <td>{{ detail.date|date("Y/m/d") }}</td>
                        <td>{{ detail.remark }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <td colspan="6">No Data!</td>
            {% endif %}
        </tbody>

    </table>
{% endblock %}